### ISSUE TITLE
Changelog entry / upgrade guide for v4?

### ISSUE THREAD

**Issue by karlhorky** [cypress-visual-regression/cypress-visual-regression#221] opened 2024-01-25 18:03 UTC
I saw that v4 of this plugin came out, thanks!

I didn't see an entry in [the `CHANGELOG.md` file](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/CHANGELOG.md) though - would it be possible to get a changelog entry here, with a note about the breaking changes?

Looking through [the (large) diff](https://github.com/cypress-visual-regression/cypress-visual-regression/compare/6fa1e92f9b49f48c767efc426095e11e12e2191b...5eb8f060c1e348c8b86eb7fa10b1079e18003861) between `3.0.0` and `4.0.0`, I was able to see some breaking changes (seems that `getCompareSnapshotsPlugin` is no more, replaced by `configureVisualRegression`):

![Screenshot 2024-01-25 at 19 00 08](https://github.com/cypress-visual-regression/cypress-visual-regression/assets/1935696/548d147e-98aa-439b-8747-69141cc8e644)

Also failed on our GitHub Actions workflow run:

```
Your configFile threw an error from: /home/runner/work/project/project/cypress.config.ts

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: getCompareSnapshotsPlugin is not a function
    at setupNodeEvents (file:///home/runner/work/project/project/cypress.config.ts:13:13)
    at /home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:122:14
    at tryCatcher (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:119:9)
    at RunPlugins.runSetupNodeEvents (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_plugins.js:59:17)
    at EventEmitter.<anonymous> (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:514:28)
    at process.<anonymous> (/home/runner/.cache/Cypress/13.6.3/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

**Comment by karlhorky** [comment] 2024-01-25 18:29
My personal upgrade diff:

`.github/workflows/ci.yml`

```diff
       - name: Cypress run
         uses: cypress-io/github-action@v6
         with:
           install: false
           start: pnpm start
           wait-on: 'http://localhost:3000'
-          env: type=actual
+          env: type=regression
```

`cypress.config.ts`

```diff
 import { defineConfig } from 'cypress';
-import getCompareSnapshotsPlugin from 'cypress-visual-regression/dist/plugin';
+import { configureVisualRegression } from 'cypress-visual-regression/dist/plugin';

 export default defineConfig({
   screenshotsFolder: './cypress/snapshots/actual',
-  trashAssetsBeforeRuns: true,
+  env: {
+    visualRegression: {
+      type: 'regression'
+    }
+  },
   e2e: {
-    setupNodeEvents(on, config) {
-      getCompareSnapshotsPlugin(on, config);
+    setupNodeEvents(on) {
+      configureVisualRegression(on);
    },
    baseUrl: 'http://localhost:3000/',
  },
```

`cypress/support/e2e.ts`

```diff
-import compareSnapshotCommand from 'cypress-visual-regression/dist/command';
+import { addCompareSnapshotCommand } from 'cypress-visual-regression/dist/command';

-compareSnapshotCommand();
+addCompareSnapshotCommand();
```

**Comment by Zaista** [comment] 2024-01-26 21:35
Hey, thanks for the info. I missed that file during the update, will take care of it

**Comment by Zaista** [comment] 2024-02-04 11:48
Changelog updated. Note that v5 was released with another set of breaking changes due to incompatible use of the `visualRegression` object in the configuration.

**Closed by Zaista** 2024-02-04 11:48 UTC

**Comment by karlhorky** [comment] 2024-02-04 12:04
Thanks! I'll take a look at the changelog entries:

- [Changelog for v4.0.0](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/CHANGELOG.md#v400)
- [Changelog for v5.0.0](https://github.com/cypress-visual-regression/cypress-visual-regression/blob/master/CHANGELOG.md#v500)
