### ISSUE TITLE
Snapshots resolution changes

### ISSUE THREAD

**Issue by huseyin-tumer** [cypress-visual-regression/cypress-visual-regression#165] opened 2023-02-16 09:10 UTC
Hello!
I am running tests with cy.viewport(414, 896).
But snapshots are saved as 414,724.

or i set different viewport bigger. it changes when running.
i tried capture option with viewport and fullPage, but issue same.
`cy.compareSnapshot('newCase', {
            capture: 'fullPage',
            errorThreshold: 0
        })`

**Comment by Lultik** [comment] 2023-03-28 15:39
The same issue: 

If I set `viewportHeight` param more the height of cypress window size, `.compareSnapshot` command captures screenshots in wrong place. 
It captures screenshot lower than expected.

**Comment by ahaavila** [comment] 2023-04-26 10:30
Any update about this issue? I'm running with the same error.

**Comment by firestar300** [comment] 2023-12-20 09:06
Any update about this issue? I'm running with the same error.

**Comment by area73** [comment] 2023-12-20 09:37
Hi, if you are getting a snapshot smaller (height or width) than the viewport it is probably because your container is not set to expand to 100%. or you set your window screen to a smaller size (see code below)

If you are getting a snapshot of double the size for example you set it to 1024,768 and you are getting an image of 2048, 1536, then the issue is different and it is related with Macbooks and retina display.
Basically when using a MacBook your screen resolution doubles the size.
That is especially annoying when you are running your snapshots locally and then trying to compare them on a CI with another OS
If that is your case and you are using Chrome, then you can set the scale factor to 1 on your Cypress config file like this:

```
 on('before:browser:launch', (browser, launchOptions) => {
        if (browser.family === 'chromium' && browser.name !== 'electron') {
          launchOptions.args.push('--window-size=1350,768')
          launchOptions.args.push('--force-device-scale-factor=1')
        }
        return launchOptions
      })
```

**Comment by area73** [comment] 2024-02-12 08:27
We are closing this issue.
If you think there is still an issue, please feel free to reopen it and provide an example to work with.

**Closed by area73** 2024-02-12 08:27 UTC
