### ISSUE TITLE
Cypress 10 compatibility

### ISSUE THREAD

**Issue by ungarida** [cypress-visual-regression/cypress-visual-regression#131] opened 2022-06-08 18:39 UTC
Cypress 10 has been released and I tried it out but it seems to mess with `cypress-visual-regression`. In fact there is a mismatch between paths when is storing the base / actual images in the image path is included the subpath of the test but when is retrieving the image for comparison it is looking for a path that is not including the subpath of the test.

In other words, given this folder structure:
```
├── integration
│   ├── components
│   │   └── Component.cy.ts
│   └── pages
│       └── page.cy.ts
```

It is storing the base into `/base/pages/page.cy.ts` but when it is comparing them it is looking for `/base/page.cy.ts` without the subpath.

**Comment by joemc11** [comment] 2022-06-10 14:19
We are seeing the same issue.  Would be great to get this resolved to move to Cypress 10, which has some great new features.

**Comment by lazurey** [comment] 2022-06-16 09:39
Same issue here.
Due to the paths of snapshots are generated dynamically [doc](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Asset-Files), I tried different ways of hard coded path but no luck.

Is there any workaround before the issue fixed? Thanks,

**Comment by mjhea0** [comment] 2022-06-17 19:23
I should have some time to review over the weekend.

**Comment by mighdoll** [comment] 2022-06-19 08:00
Created a fix here: https://github.com/mighdoll/cypress-visual-regression

Apologies that it's not a minimal patch. I refactored a bit as I was exploring the code.

**Comment by mighdoll** [comment] 2022-06-20 01:29
updated the fork to pass eslint/prettier. 

cypress 10 works for me with the following line in package.json:
`    "cypress-visual-regression": "mighdoll/cypress-visual-regression",
`

**Comment by Lasidar** [comment] 2022-06-30 18:28
Nice work @mighdoll! @mjhea0 any chance we could get these changes incorporated into the main package soon?

**Comment by lone-cloud** [comment] 2022-07-12 20:36
I had to fork the fork because the proposed solution above didn't work for typescript projects (types were defined to come from /dist which required a build), I didn't want to move the imports from /dist and because the `?.` operator was triggering some babel transform errors for me.
I built and published a working version under: `"@lone-cloud/cypress-visual-regression": "^1.8.1",`

**Comment by csnate** [comment] 2022-07-20 22:30
@lone-cloud and @mighdoll nice work! A couple of things I noticed with your additions

1. You now have to set `SNAPSHOT_BASE_DIRECTORY` in your `env` config otherwise the snapshots aren't moved to the SNAPSHOT_BASE directory when you run `env type=base` - [command.js, line 44](https://github.com/mighdoll/cypress-visual-regression/blob/master/src/command.js#L44). When you then try to run `env type=actual`, the base images can't be found since they are still in the screenshots directory and not the snapshots/base directory. This is probably due to the changes you've made in plugin.js that removed setting the local `SNAPSHOT_BASE_DIRECTORY` variable.
2. I'm able to get the images saved under spec directories correctly (i.e. `cypress/snapshots/base/SPEC_NAME/NAME-base.png`), which works if I only have all of my specs under 1 directory (i.e. `specs/SPEC_NAME`) However, if my spec files are under another directory (`specs/sub-directory/SPEC_NAME`) the `sub-directory` is not retained under the base directory. This would be a problem if I had spec files that are named the same thing under different directories. This could be related to https://github.com/cypress-io/cypress/issues/2319

I believe the first issue should be fixable or at least documented. The second one could be resolved by using the `Cypress.spec.relative` property instead of `Cypress.spec.name` in [command.js line 34](https://github.com/mighdoll/cypress-visual-regression/blob/master/src/command.js#L34). The only problem is this could create directory paths that are very long.

Somehow the screenshots are saved in the correct directories - change [plugin.js line 31](https://github.com/mighdoll/cypress-visual-regression/blob/master/src/plugin.js#L31) to `copyFile` instead of `rename` to see it in action

 [Cypress.spec docs](https://docs.cypress.io/api/cypress-api/spec#Syntax)

**Comment by lazurey** [comment] 2022-07-21 01:30
I ended up with a super simple hard coded connector between Cypress and pixelmatch.
The problem is all base images sit in the same folder so you need to make sure the name is unique, dependencies are `pixelmatch` and `pngjs`

in `cypress.config.js`, refer to https://docs.cypress.io/api/plugins/after-screenshot-api

```javascript
setupNodeEvents(on) { 
  on("after:screenshot", ({ name, path: filePath }) => {
  const baseImgSrc = fs.readFileSync(getBaseImgPath(name));
  const actualImgSrc = fs.readFileSync(path.normalize(filePath));
  const baseImg = PNG.sync.read(baseImgSrc);
  const actualImg = PNG.sync.read(actualImgSrc);
  const { width, height } = baseImg;
  const diff = new PNG({width, height});
  const diffPixels = pixelmatch(baseImg.data, actualImg.data, diff.data, width, height);
  const mismatchPercentage = (diffPixels / width / height ) ** 0.5;
  if (mismatchPercentage * 100 > threshold) {
   fs.writeFileSync(getDiffImgPath(name), PNG.sync.write(diff));
    throw Error("failed");
  }
  })
 }
```

**Comment by ungarida** [comment] 2022-07-21 07:19
@csnate thanks for the detailed analysis.  We are facing exactly the second pain point. We have our specs in a folder structure that reflects the pages folder structure and we are at risk of conflicts. An example `user/settings.spec.cy` and `account/settings.spec.cy` screenshot will end both into `settings.spec.cy` folder. Luckily not a big issue but still not optimal...

**Comment by csnate** [comment] 2022-07-25 17:42
@ungarida @lone-cloud @mighdoll 

I was able to get the sub directory structure to match the screenshots folder by using the following function:

```
const { join } = require('path');

/**
 * Gets a full path to a base/diff directory from an existing screenshot,
 * keeping the sub directory paths in tact.
 * @param string directory The full path to the root directory - base/diff
 * @param string screenshotsFolder The full path to the screenshots folder. Retrieved from config.
 * @param string path The full path of the image. Retrieved from details.
 */
function getFinalPath(directory, screenshotsFolder, path) {
    return join(directory, path.replace(screenshotsFolder, ''));
}
```

This will take a root directory (base or diff), the screenshots folder, and the `path` property from the [props from onAfterScreenshot](https://docs.cypress.io/api/commands/screenshot#Get-screenshot-info-from-the-onAfterScreenshot-callback). Used like this:

```
const compareSnapshotsPlugin = async (on, config) => {
    const { snapshotsFolder } = {
        snapshotsFolder: 'cypress/snapshots',
        ...config
    };
    const fullSnapshotsFolder = join(process.cwd(), snapshotsFolder);
    const baseDirectory = join(fullSnapshotsFolder, 'base');

    on('task', {
        async 'vr:base'(details) {
            const finalPath = getFinalPath(baseDirectory, config.screenshotsFolder, details.path);
            // finalPath is now /PWD/cypress/snapshots/base/SUB-DIRECTORY/SPEC-NAME/SPEC-NAME.png
        }
    });
```

I'm writing my own package for this now, but wanted to show you how I was getting this to work. Hopefully it'll help this package out as well

**Comment by devjvao** [comment] 2022-12-01 17:45
Hi there! I've opened the PR #139 to add compatibility to Cypress v10 based on [@mighdoll](https://github.com/mighdoll) fork and [@csnate](https://github.com/csnate) suggestions.

I would really appreciate it if you guys could take a look at the PR. I'm waiting for reviews :v:

**Comment by Zaista** [comment] 2022-12-13 19:44
Release v2.0.0 (#143) was just published, which now supports Cypress version >=10.

**Closed by Zaista** 2022-12-13 19:44 UTC
