### ISSUE TITLE
Compared screenshot path does not match initial screenshot path 

### ISSUE THREAD

**Issue by DavidGheorghe** [cypress-visual-regression/cypress-visual-regression#224] opened 2024-02-01 13:58 UTC
When `compareScreenshot` method is called it takes a screenshot in the directory specified in `cypress.config.ts`, and then it tries to compare the screenshot, but the in compared screenshot path is also added the spec name.

This is the `cypress.config.ts` file:
```
export default defineConfig({
    e2e: {
        specPattern: 'cypress/e2e/**/*.{cy,spec}.{js,jsx,ts,tsx}',
        baseUrl: 'http://localhost:4173',
        screenshotsFolder: './cypress/snapshots/base/',
        env: {
            visualRegression: {
                type: 'regression',
                baseDirectory: './cypress/snapshot/base/', // BASE_DIRECTORY,
                diffDirectory: './cypress/snapshot/diff/', // DIFF_DIRECTORY,
                generateDiff: 'fail',
                failSilently: true
            }
        },
        setupNodeEvents(on, config) {
            configureVisualRegression(on);
        }
    },
    component: {
        devServer: {
            framework: 'vue',
            bundler: 'vite'
        },
        screenshotsFolder: './cypress/snapshots/base/',
        env: {
            visualRegression: {
                type: 'regression',
                baseDirectory: './cypress/snapshot/base/',
                diffDirectory: './cypress/snapshot/diff/',
                generateDiff: 'fail',
                failSilently: true
            }
        },
        setupNodeEvents(on, config) {
            configureVisualRegression(on);
        }
    }
});
```

And for this simple test:
```
it('screenshot', () => {
      cy.mount(() => (
          <WEFrameApplicationMenu
              uuid="01"
          />
      ));
      cy.get($dsFrameApplicationMenu.root).compareSnapshot('application-menu');
  });
```

It throws this error: 
```
cy.task('compareSnapshots') failed with the following error:
> File 'cypress\snapshot\base\WEFrameApplicationMenu.cy.tsx\application-menu.png' does not exist.
```

Dependencies versions:
- Cypress version "^13.3.1"
- Vue version "^3.3.4"
- Plugin's version "^4.0.0"

**Comment by Zaista** [comment] 2024-02-04 22:45
Do you mind providing a fully reproducible example? I couldn't reproduce it with my examples.

**Comment by DavidGheorghe** [comment] 2024-02-05 08:23
@Zaista  What additional information do you need? I'd love to provide a reproducible example, but all tests fail due to the same error.

**Comment by Zaista** [comment] 2024-02-05 08:27
A project example on GitHub that I can pull & run would be perfect

**Comment by blanchecadaptive** [comment] 2024-02-05 19:13
[Compared screenshot path does not match initial screenshot path](https://github.com/cypress-visual-regression/cypress-visual-regression/issues/224#top) - is this related to the issue where it says the it failed cause the image doesnt exist even though it does?

**Comment by MIKOLAJW197** [comment] 2024-02-19 09:39
+1
same issue - copied code from "set up guide" and same issue (Angular project)

**Comment by area73** [comment] 2024-03-16 19:14
@DavidGheorghe , I'm closing this issue

Probably this PR #233 will solve your issues.

If you feel this is not addressed there, feel free to reopen it with a working example.

Thanks!

**Closed by area73** 2024-03-16 19:14 UTC
Labels: waiting for example
